- README.md
- transformer.py
Keeping open until November 6, 2019
> Fixing up README and type declarations

- transformer.py
Same as https://github.com/terraref/extractors-stereo-rgb/pull/56; to match method name in BETYdb
> update method name

- README.md
- transformer.py
moved algorithm description to the top
instructions for use below.
@ZongyangLi can you please review the algorithm description to confirm that it is still up to date?
> Updated README

- README.md
- transformer.py
The masked canopy-cover algorithm in transformer.py was changed to match the TERRA-REF algorithm
> Transformer py

- .github/workflows/testing_checks.yaml
Minor changes to workflow YAML file
Removed branch name
Improved pylint check for the test folder (don't want the files all considered together)
Added matrix app name to the artifact upload
@julianpistorius Please review
@dlebauer FYI
Successful Action run with these changes: https://github.com/AgPipeline/transformer-canopycover/actions/runs/234994729
references AgPipeline/issues-and-projects#244
> Reorganize test

- .github/workflows/testing_checks.yaml
- README.md
- tests/test_canopy_cover.py
Changed the download of test data files to refer to CyVerse
Documentation update
Check out the changes in the README
Resolves agpipeline/issues-and-projects#258
> Changing download links to CyVerse

- .github/workflows/testing_checks.yaml
- README.md
- REVIEW.adoc
- canopycover.py
- test_data/meta.yaml
- tests/test_canopy_cover.py
Changed incorrect terminology of germplasmName to `species` in documentation, code, and testing files
Also fixed testing checks for new AgPypeline library (metadata not needed)
Updated documentation to refer to correct term
Updated code to use correct term
Updated testing file to use the correct term
@julianpistorius Please review
@dlebauer FYI & review documents if desired
@jvanderleeuw Please review
Resolves issues-and-projects/issues#256
> Changing term to species

- .github/workflows/testing_checks.yaml
- README.md
- canopycover.py
- tests/test_canopy_cover.py
Removed check for 75% or better non-masked  image because it was a TERRA REF specific check
Better handling of image alpha channel by not checking for amount of masked image (see above)
Added better error reporting for debugging
@julianpistorius - Please review `canopycover.py` only
@dlebauer FYI - this PR is only for canopycover.py changes
@jvanderleeuw  - Please review `canopycover.py` only
Resolves agpipeline/issues-and-projects#263
> Alpha channel support

- .github/workflows/testing_checks.yaml
- README.md
- REVIEW.adoc
- canopycover.py
- test_data/meta.yaml
- tests/test_canopy_cover.py
Merging develop to master
Will be version 1.3 when merged
> Merging develop to master - no review

- .github/workflows/testing_checks.yaml
- .github/workflows/testing_docker.yaml
Added ability to manually start GitHub Actions - no review
> Adding manual Actions - no review

- .github/workflows/docker_test_check_rgb.sh
- .github/workflows/testing_docker.yaml
- canopycover.py
- test_data/canopycover.csv
- test_data/canopycover_geostreams.csv
- tests/test_canopy_cover.py
Removed unwanted CSV file and truncating results to significant digits
This will be version 1.4 when merged to main branch
Removed geostgeams CSV file from code and tests
Truncating calculated values to 3 significant digits per https://github.com/AgPipeline/issues-and-projects/issues/342
Updated test to correctly test truncated value
@dlebauer Please take a look at code changes if you want
@julianpistorius Please check out the code changes
@jvanderleeuw  Please check out the code changes
Part of https://github.com/AgPipeline/issues-and-projects/issues/334 and https://github.com/AgPipeline/issues-and-projects/issues/342
> Truncating to significant digits, removed geostreams csv

- canopycover.py
- tests/test_canopy_cover.py
Refer to issue https://github.com/AgPipeline/issues-and-projects/issues/347 (which links to https://hackmd.io/Bbe_POvwQN6uN18jCDlugA?view containing the specifics)
This PR adds the ability to specify species name on a per plot basis
This will be v 1.4 when merged
> Plot handling - no review

- .github/workflows/docker_test_check_rgb.sh
- canopycover.py
- test_data/canopycover.csv
- test_data/canopycover_geostreams.csv
- tests/test_canopy_cover.py
Handling species on a per plot basis, removed some csv fields per https://github.com/AgPipeline/issues-and-projects/issues/347 (see https://hackmd.io/Bbe_POvwQN6uN18jCDlugA?view - the CSV file comments)
Will be v1.4 when merged
> Merge develop to main branch - no review

- canopycover.py
Handling new empty timestamp from AgPypeline library. No review
> Handling updated AgPypeline library

- .github/workflows/testing_checks.yaml
- README.md
Updated readme to have badges
Added badges to readme
> Add badges

- .github/workflows/testing_checks.yaml
- .github/workflows/testing_docker.yaml
- Dockerfile
- canopycover.py
- tests/test_canopy_cover.py
Updated to Ubuntu 20.l04 - no review
Will be v1.7 when merged
> Merging develop to main branch - no review

- .github/workflows/testing_checks.yaml
Merge develop to main - Actions fix
> Merge develop to main

- canopycover.py
Suppressing new pylint message - no review
> Suppressing new pylint message - no review

- canopycover.py
Merging suppression of new pylint message -no review
> Merging suppression of new pylint message -no review

- .github/workflows/testing_checks.yaml
- Dockerfile
> Fixing setuptools/pygdal issue

- .github/workflows/testing_checks.yaml
- Dockerfile
> Merging setuptools versioning fix

- canopycover.py
> Updating actions for new pylint messages

- canopycover.py
> Merging pylint actions fix to main branch

- canopycover.py
> Fixing Actions pylint
